#!/bin/bash
source "$HOME/.local/share/scripts/kncs_variables.sh"
source "$script_dir/kncs_enable_disable.sh"

function user_input {
  # Check if zenity is installed
  if ! command -v zenity >/dev/null 2>&1; then
      echo "Error: zenity is not installed. Please install it with 'sudo apt install zenity'."
      exit 1
  fi
  # Check if curl is installed
  if ! command -v curl >/dev/null 2>&1; then
      echo "Error: curl is not installed. Please install it with 'sudo apt install curl'."
      exit 1
  fi
  # Create form dialog
  RESPONSE=$(zenity --forms \
      --text="  Enter your Nextcloud URL, App credentials and sync folder" \
      --add-entry="Nextcloud URL (ex. cloud.example.com)" \
      --add-entry="Username" \
      --add-password="Password" \
      --add-entry="Sync Folder (ex. /home/user/Nextcloud)" \
      --width=500 --height=300 2>/dev/null)
  # Check if user clicked OK (0) or Cancel (1)
  if [ $? -ne 0 ]; then
      zenity --error --title="Error" --text="Input cancelled. Exiting." --width=300
      exit 1
  fi
  # Split response into variables
  IFS='|' read -r NC_URL NC_USERNAME NC_PASSWORD NC_PATH <<< "$RESPONSE"
  # Validate inputs
  if [ -z "$NC_URL" ] || [ -z "$NC_USERNAME" ] || [ -z "$NC_PASSWORD" ] || [ -z "$NC_PATH" ]; then
      zenity --error --title="Error" --text="One or more fields were empty. Please try again." --width=300
      exit 1
  fi
  # Test Nextcloud connection
  # Step 1: Check server availability via /status.php
  curl --silent --fail --http1.1 --connect-timeout 5 "https://$NC_URL/status.php" >/dev/null
  if [ $? -ne 0 ]; then
      zenity --error --title="Connection Error" --text="Failed to connect to $NC_URL. Please check the URL and network." --width=300
      exit 1
  fi
  # Step 2: Verify credentials via WebDAV endpoint
  curl --silent --fail --http1.1 --user "$NC_USERNAME:$NC_PASSWORD" --head "https://$NC_URL/remote.php/dav/files/$NC_USERNAME/" >/dev/null
  if [ $? -ne 0 ]; then
      zenity --error --title="Authentication Error" --text="Invalid username or password for $NC_URL." --width=300
      exit 1
  fi
  # Validate sync path (check if directory exists)
  if [ ! -d "$NC_PATH" ]; then
      zenity --error --title="Error" --text="The sync path '$NC_PATH' does not exist or is not a directory." --width=300
      exit 1
  fi

  # Display confirmation
  busctl --user call org.kde.kwalletd5 /modules/kwalletd5 org.kde.KWallet writePassword issss "$kwallet_id" "Nextcloud" "MENU:$NC_USERNAME:$NC_URL:$NC_PATH" "$NC_PASSWORD" ""
  echo -e "# Created $(date)\n# This log file is used to log your share urls generated by the KDE Nextcloud Context Menu with their expiration dates.\n# ------------------------" > $NC_PATH/.kdencservicemenu
  # Switch servicemenus
  enable_disable
  zenity --info --title="Connection Successful" --text="Your credentials have been saved in Kwallet\nA log file named .kdencservicemenu was created in your Nextcloud home directory" --width=400
}
user_input
